artifact_uri: file:///workspace/qlib_workspace/mlruns/1/37716ba581664a6c865f52aec6449f40/artifacts
end_time: 1738051207506
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 37716ba581664a6c865f52aec6449f40
run_name: mlflow_recorder
run_uuid: 37716ba581664a6c865f52aec6449f40
source_name: ''
source_type: 4
source_version: ''
start_time: 1738051168537
status: 3
tags: []
user_id: root
