artifact_uri: file:///workspace/qlib_workspace/mlruns/1/77b227f86e5a47bab48178cac409a98b/artifacts
end_time: 1738043659281
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 77b227f86e5a47bab48178cac409a98b
run_name: mlflow_recorder
run_uuid: 77b227f86e5a47bab48178cac409a98b
source_name: ''
source_type: 4
source_version: ''
start_time: 1738043624771
status: 3
tags: []
user_id: root
