artifact_uri: file:///workspace/qlib_workspace/mlruns/1/60a7b861fc6d4fbd964c04bb414493eb/artifacts
end_time: 1738045289759
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 60a7b861fc6d4fbd964c04bb414493eb
run_name: mlflow_recorder
run_uuid: 60a7b861fc6d4fbd964c04bb414493eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1738045218843
status: 3
tags: []
user_id: root
